---
title: "penguins_tidy_modeling"
author: "Erwin Lares"
date: "2023-02-13"
output: html_document
---

```{r setup}
# Packages ----
library(palmerpenguins)
library(tidymodels)
```
## Data
```{r}
penguins <- palmerpenguins::penguins
```

```{r}
(filtered_penguins <- penguins %>% 
  drop_na(ends_with("mm")))
```
## Exploration
```{r}
filtered_penguins %>% 
  ggplot(aes(x = bill_length_mm, y = bill_depth_mm, col = species)) +
  geom_point()
```

```{r}
filtered_penguins %>% 
  select(species, ends_with("mm"), body_mass_g)
```
## Model Fit
```{r}
model <- rand_forest() %>% 
  set_engine("ranger") %>% 
  set_mode("classification") %>% 
  fit(species ~ bill_length_mm + bill_depth_mm + flipper_length_mm + body_mass_g, data = filtered_penguins)
```

```{r}
model
```

```{r}

sim_data <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1HEQa23hR202egPcnyAtQHGyPRw1WWv61H6aHnAhjcrc/edit#gid=519943868")

predict(model, new_data = sample(sim_data, size = 25, replace = TRUE), type = "prob")
```

## Model Performance
```{r}
sim_data %>% 
  bind_cols(predict(model, new_data = sim_data)) %>% 
  count(species, .pred_class)
```

## Model Export
```{r}
readr::write_rds(model, here::here("penguin_predict/", "model.rds"))
```



